function [actual_ddf_at_zero, counter] =...
    Blaius_shooting_wrapping(initial_guess)
    
    [actual_ddf_at_zero, counter] = ...
        new_raph_rf(@Blasius_Wrapping, initial_guess, 1e-10, 1000, 0, 1);
end